site_name: bayesian-filters-smoothers
site_url: https://github.com/ninadkgaikwad/bayseian-filters-smoothers
nav:
  - Home: index.md
  - User Guide: userguide.md
  - API: api_reference.md

theme: readthedocs

plugins: 
    - mkdocstrings:
        handlers:
            python:
                setup_commands:
                    - import sys
                    - sys.path.append('../bayesian-filters-smoothers/bayesian_filters_smoothers/')
